# Default stylesheet for rustloc CLI

# Bold styling for table headers
header:
  fg: cyan
  bold: true

# Alternating row styling
row_alt:
  dim: true

# Diff additions (green)
additions:
  fg: green

# Diff deletions (red)
deletions:
  fg: red
